#!/bin/bash



function makehack {
cd /boot
cp start_x.elf start_x.elf_backup && \
 perl -pne 's/\x47\xE9362H\x1D\x18/\x47\xE9362H\x1D\x1F/g' < start_x.elf_backup$

echo "MPG2 and WVC1 codeds enabled"
}

if [ $(uname -a | grep osmc | wc -l) -gt 0 ]
then
t1=$(vcgencmd codec_enabled MPG2)
t2=$(vcgencmd codec_enabled WVC1)
if [ "$t1" != "MPG2=enabled" ] || [ "$t2" != "WVC1=enabled" ]
        then
                makehack
        else
                echo "Codecs already enabled"
        fi
else
        echo "No OSMC"
fi
